import type { Metadata } from "next"
import { Sora, Source_Code_Pro, Space_Grotesk } from "next/font/google"

import "./globals.css"

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/app/components/theme-provider"

const fontSans = Sora({ subsets: ["latin"], variable: "--font-sans" })
const fontCode = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-code",
})
const fontGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          fontSans.variable,
          fontCode.variable,
          fontGrotesk.variable,
          "font-sans"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
